name: Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  runnerSetup:
    uses: ./.github/workflows/_runner_setup.yml
    with:
      os: ${{ inputs.os }}

  uploadArtifacts:
    needs: [runnerSetup]
    runs-on: ${{ needs.runnerSetup.outputs.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        if: ${{ inputs.os == 'linux' }}
        run: ./install_build_dependencies_linux.sh

      - run: cargo build --release

      - name: Make artifacts folder
        run: mkdir artifacts

      - name: Add artifacts to folder
        if: ${{ inputs.os == 'linux' }}
        run: |
          cp target/release/loregui artifacts
          cp target/release/liblorecore.so artifacts
          cp lorecore_api.h artifacts

      - name: Add artifacts to folder
        if: ${{ inputs.os == 'windows' }}
        run: |
          cp target/release/loregui.exe artifacts
          cp target/release/liblorecore.dll artifacts
          cp lorecore_api.h artifacts

      - name: Add artifacts to folder
        if: ${{ inputs.os == 'macos' }}
        run: |
          cp target/release/loregui artifacts
          cp target/release/liblorecore.dylib artifacts
          cp lorecore_api.h artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LoreCoreLibrary_${{ inputs.os}}
          path: artifacts
