name: Build

on:
  workflow_call:
    inputs:
      isRelease:
        type: boolean
        required: false
        default: false

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./install_build_dependencies_linux.sh

      - run: cargo build --release
        if: ${{ inputs.isRelease }}

      - run: |
          cargo build
          exit 0
        if: ${{ !inputs.isRelease }}

      - name: Make artifacts folder
        run: mkdir artifacts

      - name: Add artifacts to folder
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cp target/release/loregui artifacts
          cp target/release/liblorecore.so artifacts
          cp lorecore_api.h artifacts

      - name: Add artifacts to folder
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cp target/release/loregui.exe artifacts
          cp target/release/liblorecore.dll artifacts
          cp lorecore_api.h artifacts

      - name: Add artifacts to folder
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cp target/release/loregui artifacts
          cp target/release/liblorecore.dylib artifacts
          cp lorecore_api.h artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LoreCoreLibrary_${{ matrix.os}}
          path: artifacts
