name: Runner Setup

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  runnerSetup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check branch
        id: step1
        run: |
          if [ ${{ inputs.os }} == 'linux' ]; then
            echo "::set-output name=runner::ubuntu-latest"
          elif [ ${{ inputs.os }} == 'windows' ]; then
            echo "::set-output name=runner::windows-latest"
          elif [ ${{ inputs.os }} == 'macos' ]; then
            echo "::set-output name=runner::macos-latest"
          fi