name: Tests
on: [workflow_call]

jobs:
    buildAndTest:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
  
        - name: Install dependencies for Linux
          if: matrix.os == 'ubuntu-latest'
          run: |
            sudo apt-get update
            sudo apt-get install -y sudo curl build-essential cmake pkg-config libfontconfig1-dev cargo
  
        - uses: dtolnay/rust-toolchain@stable
          with:
              toolchain: stable
  
        - uses: clechasseur/rs-cargo@v3
          if: ${{ github.ref_name != 'main' }}
          with:
              command: test
              args: -- --nocapture
  
        - uses: clechasseur/rs-cargo@v3
          if: ${{ github.ref_name == 'main' }}
          with:
              command: test
              args: --release -- --nocapture

        - uses: clechasseur/rs-cargo@v3
          with:
              command: clippy