name: Debug Build

on: [push]

jobs:
  buildDebug:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout changelog
      uses: Bhacaz/checkout-files@v2
      with:
        files: CHANGELOG.md

    - name: Display file structure
      run: ls -R
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ./install_build_dependencies_linux.sh
    - name: Build
      run: cargo build --verbose
