name: Regular Build

on:
  schedule:
    - cron: "0 0 * * 5" # every Friday at 00:00 UTC

jobs:
  releaseBuild:
    uses: ./.github/workflows/_build.yml
    with:
      isRelease: false

  testExecutability:
    needs: [releaseBuild]
    uses: ./.github/workflows/_test_executability.yml
    
