name: Release Binaries

on:
  [push]
  # push:
  #   branches: ["main"]

jobs:
  buildLinux:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./install_build_dependencies_linux.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release

      - name: Create a temporary artifact downloads folder
        run: mkdir artifacts

      - name: Add artifacts to folder
        run: |
          cp target/release/liblorecore.so artifacts
          cp lorecore_api.h artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LoreCoreLibrary
          path: artifacts
