name: Test Lua

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v3
        - run: ./scripts/install_lua_dependencies_linux.sh
          if: matrix.os == 'ubuntu-latest'
        - run: ./scripts/install_lua_dependencies_macos.sh
          if: matrix.os == 'macos-latest'
        - run: ./scripts/install_lua_dependencies_windows.sh
          if: matrix.os == 'windows-latest'
