name: Run Tests
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 0 * * 6" # every saturday at 00:00 UTC

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
  
        - name: Install dependencies for Linux
          if: matrix.os == 'ubuntu-latest'
          run: |
            sudo apt-get update
            sudo apt-get install -y sudo curl build-essential cmake pkg-config libfontconfig1-dev cargo
            ./scripts/install_build_dependencies_linux.sh
        - name: Install dependencies for Windows
          if: matrix.os == 'windows-latest'
          run: |
            .\scripts\install_build_dependencies_windows.bat
        - name: Install dependencies for MacOS
          if: matrix.os == 'macos-latest'
          run: |
            chmod +x ./scripts/install_build_dependencies_macos.sh
            ./scripts/install_build_dependencies_macos.sh
  
        - uses: dtolnay/rust-toolchain@stable
          with:
              toolchain: stable
  
        - uses: clechasseur/rs-cargo@v1
          if: ${{ github.ref_name != 'main' }}
          with:
              command: test
  
        - uses: clechasseur/rs-cargo@v1
          if: ${{ github.ref_name == 'main' }}
          with:
              command: test
              args: --release