name: Test Releasing Binaries

on: [push]

jobs:
  buildLinux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Add mock artifacts to folder
        run: |
          mkdir artifacts
          touch artifacts/oneFile
          touch artifacts/secondFile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LoreCoreLinuxLibrary
          path: artifacts

  publishBinaries:
    name: Publish Binaries
    runs-on: ubuntu-latest
    needs: [buildLinux]
    permissions: write-all

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: LoreCoreLinuxLibrary
          path: artifactsLinux

      - name: Create CHANGELOG.md
        run: touch CHANGELOG.md

      - name: Check Files
        run: ls -l artifactsLinux/*

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: v0.0.0
          tag_name: $v0.0.0
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifactsLinux/*